server:
  port: 9899
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/app
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mail:
    host: smtp.gmail.com
    password: Saireddy@96
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: saijava1996@gmail.com
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      
forgotpassword-app:
  messages:
    forgotPwdMailSubject: Forgot Password-Sai  
    forgotPasswordMailBodyTemplateFile: FORGOT-PASSWORD-EMAIL-BODY.txt  
      
   
      
